# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuizDown.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(863, 716)
        Form.setMinimumSize(QtCore.QSize(500, 500))
        Form.setStyleSheet("background-image: url(:/new/prefix1/Graphics/Background Clean.png);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setStyleSheet("font: 14pt \"Gadugi\";")
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.stackedWidgetPage1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.stackedWidgetPage1)
        self.pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setToolTipDuration(0)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/Start_quiz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(150, 75))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.quest_label = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.quest_label.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.quest_label.setObjectName("quest_label")
        self.verticalLayout.addWidget(self.quest_label, 0, QtCore.Qt.AlignHCenter)
        self.ques_combo = QtWidgets.QComboBox(self.stackedWidgetPage1)
        self.ques_combo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ques_combo.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.ques_combo.setStyleSheet("font: 12pt \"Arial Rounded MT Bold\";\n"
"background-color: rgb(255, 246, 246);\n"
"")
        self.ques_combo.setObjectName("ques_combo")
        self.verticalLayout.addWidget(self.ques_combo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.dif_label = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.dif_label.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.dif_label.setObjectName("dif_label")
        self.verticalLayout_2.addWidget(self.dif_label, 0, QtCore.Qt.AlignHCenter)
        self.diff_combo = QtWidgets.QComboBox(self.stackedWidgetPage1)
        self.diff_combo.setMinimumSize(QtCore.QSize(150, 0))
        self.diff_combo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.diff_combo.setStyleSheet("font: 12pt \"Arial Rounded MT Bold\";\n"
"background-color: rgb(255, 246, 246);")
        self.diff_combo.setObjectName("diff_combo")
        self.verticalLayout_2.addWidget(self.diff_combo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem6)
        self.cata_label = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.cata_label.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.cata_label.setObjectName("cata_label")
        self.verticalLayout_3.addWidget(self.cata_label, 0, QtCore.Qt.AlignHCenter)
        self.cata_combo = QtWidgets.QComboBox(self.stackedWidgetPage1)
        self.cata_combo.setMinimumSize(QtCore.QSize(150, 0))
        self.cata_combo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cata_combo.setStyleSheet("font: 12pt \"Arial Rounded MT Bold\";\n"
"background-color: rgb(255, 246, 246);")
        self.cata_combo.setObjectName("cata_combo")
        self.verticalLayout_3.addWidget(self.cata_combo, 0, QtCore.Qt.AlignHCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_2.setMinimumSize(QtCore.QSize(0, 250))
        self.label_2.setStyleSheet("image: url(:/new/prefix1/Graphics/Logo2.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_4.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit = QtWidgets.QLineEdit(self.stackedWidgetPage1)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit.setStyleSheet("font: 10pt \"Gill Sans Ultra Bold\";")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_7.addWidget(self.lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.stackedWidgetPage1)
        self.label_5.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.stackedWidgetPage1)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_2.setStyleSheet("font: 10pt \"Gill Sans Ultra Bold\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_8.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 4, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.stackedWidgetPage2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(420, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 6, 0, 1, 3)
        self.tab_quest_label = QtWidgets.QTextBrowser(self.stackedWidgetPage2)
        self.tab_quest_label.setStyleSheet("font: 18pt \"Gadugi\";\n"
"background-image: url(:/new/prefix1/Graphics/Background Grey.png);")
        self.tab_quest_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tab_quest_label.setCursorWidth(1)
        self.tab_quest_label.setPlaceholderText("")
        self.tab_quest_label.setObjectName("tab_quest_label")
        self.gridLayout_3.addWidget(self.tab_quest_label, 3, 1, 1, 5)
        self.Player_1 = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.Player_1.setMaximumSize(QtCore.QSize(100, 100))
        self.Player_1.setText("")
        self.Player_1.setPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/player 1.png"))
        self.Player_1.setScaledContents(True)
        self.Player_1.setObjectName("Player_1")
        self.gridLayout_3.addWidget(self.Player_1, 0, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 280, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem12, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem13)
        self.ans_lineEdit = QtWidgets.QLineEdit(self.stackedWidgetPage2)
        self.ans_lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.ans_lineEdit.setStyleSheet("font: 18pt \"Gadugi\";")
        self.ans_lineEdit.setObjectName("ans_lineEdit")
        self.horizontalLayout_2.addWidget(self.ans_lineEdit)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem14)
        self.check_answer_button = QtWidgets.QPushButton(self.stackedWidgetPage2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/Check_answer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check_answer_button.setIcon(icon1)
        self.check_answer_button.setIconSize(QtCore.QSize(55, 55))
        self.check_answer_button.setFlat(True)
        self.check_answer_button.setObjectName("check_answer_button")
        self.horizontalLayout_2.addWidget(self.check_answer_button)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem15)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 0, 2, 7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.skip_button = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.skip_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/skip_question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skip_button.setIcon(icon2)
        self.skip_button.setIconSize(QtCore.QSize(100, 50))
        self.skip_button.setFlat(True)
        self.skip_button.setObjectName("skip_button")
        self.horizontalLayout.addWidget(self.skip_button)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem17)
        self.cont_button = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.cont_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/next_question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cont_button.setIcon(icon3)
        self.cont_button.setIconSize(QtCore.QSize(100, 50))
        self.cont_button.setFlat(True)
        self.cont_button.setObjectName("cont_button")
        self.horizontalLayout.addWidget(self.cont_button)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem18)
        self.gridLayout_3.addLayout(self.horizontalLayout, 7, 0, 3, 7)
        spacerItem19 = QtWidgets.QSpacerItem(15, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem19, 10, 3, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 0, 6, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 225))
        self.label.setStyleSheet("image: url(:/new/prefix1/Graphics/Logo2.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 3)
        self.hint_button = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.hint_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/Hint_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hint_button.setIcon(icon4)
        self.hint_button.setIconSize(QtCore.QSize(40, 40))
        self.hint_button.setFlat(True)
        self.hint_button.setObjectName("hint_button")
        self.gridLayout_3.addWidget(self.hint_button, 6, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(420, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 6, 4, 1, 3)
        self.Question_tracker = QtWidgets.QLabel(self.stackedWidgetPage2)
        self.Question_tracker.setStyleSheet("font: 18pt \"Gadugi\";")
        self.Question_tracker.setText("")
        self.Question_tracker.setAlignment(QtCore.Qt.AlignCenter)
        self.Question_tracker.setObjectName("Question_tracker")
        self.gridLayout_3.addWidget(self.Question_tracker, 1, 4, 1, 2)
        self.stackedWidget.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.stackedWidgetPage3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem23)
        self.finish_button = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.finish_button.setMaximumSize(QtCore.QSize(200, 150))
        self.finish_button.setText("")
        self.finish_button.setPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/Finish.png"))
        self.finish_button.setScaledContents(True)
        self.finish_button.setObjectName("finish_button")
        self.horizontalLayout_7.addWidget(self.finish_button)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem24)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 4, 1, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.result_winner_p2 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_winner_p2.setMinimumSize(QtCore.QSize(150, 150))
        self.result_winner_p2.setMaximumSize(QtCore.QSize(150, 150))
        self.result_winner_p2.setText("")
        self.result_winner_p2.setScaledContents(True)
        self.result_winner_p2.setObjectName("result_winner_p2")
        self.verticalLayout_5.addWidget(self.result_winner_p2, 0, QtCore.Qt.AlignHCenter)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem25)
        self.result_name_p2 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_name_p2.setMinimumSize(QtCore.QSize(120, 60))
        self.result_name_p2.setMaximumSize(QtCore.QSize(999, 100))
        self.result_name_p2.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.result_name_p2.setText("")
        self.result_name_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.result_name_p2.setObjectName("result_name_p2")
        self.verticalLayout_5.addWidget(self.result_name_p2)
        self.result_score_p2 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_score_p2.setMinimumSize(QtCore.QSize(120, 60))
        self.result_score_p2.setMaximumSize(QtCore.QSize(999, 100))
        self.result_score_p2.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.result_score_p2.setText("")
        self.result_score_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.result_score_p2.setObjectName("result_score_p2")
        self.verticalLayout_5.addWidget(self.result_score_p2)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem26)
        self.result_icon_p2 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_icon_p2.setMaximumSize(QtCore.QSize(100, 100))
        self.result_icon_p2.setText("")
        self.result_icon_p2.setPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/Player 2.png"))
        self.result_icon_p2.setScaledContents(True)
        self.result_icon_p2.setObjectName("result_icon_p2")
        self.verticalLayout_5.addWidget(self.result_icon_p2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 3, 2, 2, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.result_winner_p1 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_winner_p1.setMinimumSize(QtCore.QSize(0, 150))
        self.result_winner_p1.setMaximumSize(QtCore.QSize(150, 150))
        self.result_winner_p1.setText("")
        self.result_winner_p1.setScaledContents(True)
        self.result_winner_p1.setObjectName("result_winner_p1")
        self.verticalLayout_4.addWidget(self.result_winner_p1, 0, QtCore.Qt.AlignHCenter)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem27)
        self.result_name_p1 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_name_p1.setMinimumSize(QtCore.QSize(120, 60))
        self.result_name_p1.setMaximumSize(QtCore.QSize(999, 100))
        self.result_name_p1.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.result_name_p1.setText("")
        self.result_name_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.result_name_p1.setObjectName("result_name_p1")
        self.verticalLayout_4.addWidget(self.result_name_p1)
        self.result_score_p1 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_score_p1.setMinimumSize(QtCore.QSize(120, 60))
        self.result_score_p1.setMaximumSize(QtCore.QSize(999, 100))
        self.result_score_p1.setStyleSheet("font: 14pt \"Gill Sans Ultra Bold\";")
        self.result_score_p1.setText("")
        self.result_score_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.result_score_p1.setObjectName("result_score_p1")
        self.verticalLayout_4.addWidget(self.result_score_p1)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem28)
        self.result_icon_p1 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.result_icon_p1.setMaximumSize(QtCore.QSize(100, 100))
        self.result_icon_p1.setText("")
        self.result_icon_p1.setPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/player 1.png"))
        self.result_icon_p1.setScaledContents(True)
        self.result_icon_p1.setObjectName("result_icon_p1")
        self.verticalLayout_4.addWidget(self.result_icon_p1, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 3, 0, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_3.setMinimumSize(QtCore.QSize(500, 200))
        self.label_3.setMaximumSize(QtCore.QSize(500, 300))
        self.label_3.setStyleSheet("image: url(:/new/prefix1/Graphics/Logo2.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem29, 0, 0, 1, 1)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem30, 0, 2, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.stackedWidgetPage3)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(7)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.tableWidget, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.label_6.setMaximumSize(QtCore.QSize(350, 50))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/new/prefix1/Graphics/Highscore.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.stackedWidgetPage3)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QuizDown"))
        self.quest_label.setText(_translate("Form", "Number of questions"))
        self.dif_label.setText(_translate("Form", "Difficulty"))
        self.cata_label.setText(_translate("Form", "Category"))
        self.label_4.setText(_translate("Form", "Player 1"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter name .."))
        self.label_5.setText(_translate("Form", "Player 2"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Enter name .."))
        self.tab_quest_label.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gadugi\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ans_lineEdit.setPlaceholderText(_translate("Form", "Please enter your answer.."))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Score"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Name"))

import myndir_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

