# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuizDown.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(745, 536)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 751, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.front_tab = QtWidgets.QWidget()
        self.front_tab.setEnabled(True)
        self.front_tab.setObjectName("front_tab")
        self.pushButton = QtWidgets.QPushButton(self.front_tab)
        self.pushButton.setGeometry(QtCore.QRect(520, 460, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.diff_combo = QtWidgets.QComboBox(self.front_tab)
        self.diff_combo.setGeometry(QtCore.QRect(210, 430, 174, 20))
        self.diff_combo.setObjectName("diff_combo")
        self.head_label = QtWidgets.QLabel(self.front_tab)
        self.head_label.setGeometry(QtCore.QRect(280, 0, 171, 61))
        self.head_label.setObjectName("head_label")
        self.quest_label = QtWidgets.QLabel(self.front_tab)
        self.quest_label.setGeometry(QtCore.QRect(90, 400, 99, 20))
        self.quest_label.setObjectName("quest_label")
        self.ques_combo = QtWidgets.QComboBox(self.front_tab)
        self.ques_combo.setGeometry(QtCore.QRect(210, 400, 174, 20))
        self.ques_combo.setObjectName("ques_combo")
        self.cata_label = QtWidgets.QLabel(self.front_tab)
        self.cata_label.setGeometry(QtCore.QRect(88, 370, 111, 20))
        self.cata_label.setObjectName("cata_label")
        self.info_label = QtWidgets.QLabel(self.front_tab)
        self.info_label.setGeometry(QtCore.QRect(90, 50, 131, 121))
        self.info_label.setObjectName("info_label")
        self.dif_label = QtWidgets.QLabel(self.front_tab)
        self.dif_label.setGeometry(QtCore.QRect(90, 430, 99, 20))
        self.dif_label.setObjectName("dif_label")
        self.cata_combo = QtWidgets.QComboBox(self.front_tab)
        self.cata_combo.setGeometry(QtCore.QRect(210, 370, 174, 20))
        self.cata_combo.setObjectName("cata_combo")
        self.tabWidget.addTab(self.front_tab, "")
        self.quest_tab = QtWidgets.QWidget()
        self.quest_tab.setEnabled(False)
        self.quest_tab.setObjectName("quest_tab")
        self.tab_quest_label = QtWidgets.QLabel(self.quest_tab)
        self.tab_quest_label.setGeometry(QtCore.QRect(30, 80, 671, 121))
        self.tab_quest_label.setText("")
        self.tab_quest_label.setObjectName("tab_quest_label")
        self.player_label = QtWidgets.QLabel(self.quest_tab)
        self.player_label.setGeometry(QtCore.QRect(550, 20, 71, 16))
        self.player_label.setObjectName("player_label")
        self.ans_lineEdit = QtWidgets.QLineEdit(self.quest_tab)
        self.ans_lineEdit.setGeometry(QtCore.QRect(30, 220, 561, 21))
        self.ans_lineEdit.setObjectName("ans_lineEdit")
        self.hint_button = QtWidgets.QPushButton(self.quest_tab)
        self.hint_button.setGeometry(QtCore.QRect(330, 270, 75, 23))
        self.hint_button.setObjectName("hint_button")
        self.skip_button = QtWidgets.QPushButton(self.quest_tab)
        self.skip_button.setGeometry(QtCore.QRect(110, 400, 75, 23))
        self.skip_button.setObjectName("skip_button")
        self.cont_button = QtWidgets.QPushButton(self.quest_tab)
        self.cont_button.setGeometry(QtCore.QRect(510, 400, 75, 23))
        self.cont_button.setObjectName("cont_button")
        self.check_answer_button = QtWidgets.QPushButton(self.quest_tab)
        self.check_answer_button.setGeometry(QtCore.QRect(620, 220, 81, 23))
        self.check_answer_button.setObjectName("check_answer_button")
        self.tabWidget.addTab(self.quest_tab, "")
        self.results_tab = QtWidgets.QWidget()
        self.results_tab.setEnabled(False)
        self.results_tab.setObjectName("results_tab")
        self.finish_button = QtWidgets.QPushButton(self.results_tab)
        self.finish_button.setGeometry(QtCore.QRect(600, 450, 75, 23))
        self.finish_button.setObjectName("finish_button")
        self.result_label = QtWidgets.QLabel(self.results_tab)
        self.result_label.setGeometry(QtCore.QRect(100, 40, 511, 311))
        self.result_label.setObjectName("result_label")
        self.tabWidget.addTab(self.results_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QuizDown"))
        self.pushButton.setText(_translate("Form", "Start Quiz"))
        self.head_label.setText(_translate("Form", "QuizDown"))
        self.quest_label.setText(_translate("Form", "Number of questions"))
        self.cata_label.setText(_translate("Form", "Categories"))
        self.info_label.setText(_translate("Form", "Description here...."))
        self.dif_label.setText(_translate("Form", "Difficulty"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.front_tab), _translate("Form", "QuizDown"))
        self.player_label.setText(_translate("Form", "Player"))
        self.ans_lineEdit.setPlaceholderText(_translate("Form", "Please enter your answer.."))
        self.hint_button.setText(_translate("Form", "Hint"))
        self.skip_button.setText(_translate("Form", "Skip"))
        self.cont_button.setText(_translate("Form", "Continue"))
        self.check_answer_button.setText(_translate("Form", "Check Answer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.quest_tab), _translate("Form", "Questions"))
        self.finish_button.setText(_translate("Form", "Finish"))
        self.result_label.setText(_translate("Form", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.results_tab), _translate("Form", "Results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

